SELECT DISTINCT
    AF.MUNICÍPIO,
    COUNT(AF.IDATRACACAO) AS 'NÚMERO DE ATRACAÇÕES',
    AVG(DATEDIFF(HOUR,AF.DATA INÍCIO OPERAÇÃO,AF.DATA TÉRMINO OPERAÇÃO) AS 'TEMPO DE ESPERA MÉDIO',
    AVG(DATEDIFF(HOUR,AF.DATA ATRACAÇÃO,AF.DATA DESATRACAÇÃO), 
    AF.MES,
    AF.ANO

FROM
    ATRACAO_FATO AS AF
    LEFT JOIN CARGA_FATO AS CF ON CF.IDATRACACAO = AF.IDATRACACAO

WHERE AF.UF = 'CEARÁ' AND AF.REGIÃO GEOGRÁFICA = 'NORDESTE'

GROUP BY AF.MUNICÍPIO, AF.MES, AF.ANO
